### ISSUE TITLE
Computational time

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/StochasticDiffEq.jl#232] opened 2019-09-13 16:43 UTC
Hi all,

first of all, I would like to congratulate all the JuliaDiffEq team, it seems to me that the DifferentialEquations.jl suite is really complete and powerful. 

I have performed some tests directly in Julia and run [this](http://docs.juliadiffeq.org/latest/tutorials/sde_example.html#Example-1:-Scalar-SDEs-1) test, including  [Ensemble Simulations](http://docs.juliadiffeq.org/latest/tutorials/sde_example.html#Ensemble-Simulations-1) using 1e6 trajectories. The example is about a Black-Scholes model, i.e., the drift and diffusion terms are just a constant time the process. When using a low order scheme, like `EM()` with `dt=1/252` and `tspan=(0.0,1.0)` one would expect a really, really low computational cost and time, but we encounter that it took a lot of time. Do you face the same issue or is just a thing about configuration? We have tested it in MacOS, Windows and Debian operating systems. The code is:
```Julia
using DifferentialEquations
α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
sol = solve(ensembleprob,EM(),trajectories=1000000,dt=dt)
```
For me, it is a memory leak. I do not code in Julia, but in `C` it would probably be that since the computational time from 1e3 to 1e4 or 1e5 does not grow linearly. 

Additionally, I wanted to ask you if the `StochasticDiffEq.jl` source code relies in any low level library at all or if it is Julia code written by the JuliaDiffEq team. 

Please, let me know if you think we can run fast SDEs simulations using `StochasticDiffEq.jl`.

Thanks!

Ramiro.

**Comment by ChrisRackauckas** [comment] 2019-09-14 15:17
Hey, 
  Yes, getting maximal speed is always a priority here, and any time we have something not performing well in benchmarks we consider that a high priority bug. Can you give us some concrete numbers we should be seeing here?

We test against C and Fortran implementations whenever we can, and the ODE solvers routinely demonstrate being the most efficient there is in [DiffEqBenchmarks.jl](https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl). That said, for SDEs there's no other implementation of most of these methods/algorithms, so there's not much to test against, and so we usually rely on regression test against the ODE solvers. 

If you have a C/Fortran implementation that we can test against, it would be great if we can get it wrapped in a package to put on the common interface. All you need to do is create a new package that adds a dispatch, like [Sundials.jl](https://github.com/JuliaDiffEq/Sundials.jl). Writing your own implementation of a method is not difficult either, so for example [SimpleDiffEq.jl's Euler-Maruyama is 26 lines](https://github.com/JuliaDiffEq/SimpleDiffEq.jl/blob/master/src/euler_maruyama.jl) and just hooks into the system.

Since that's just a simple loop, it should be as fast as something in C/Fortran (if it's not, then this would be good to investigate). So I tested:

```julia
using DifferentialEquations
α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
@time sol = solve(ensembleprob,SimpleEM(),trajectories=1000000,dt=dt)
@time sol = solve(ensembleprob,EM(),trajectories=1000000,dt=dt)
```

says it's about 100 seconds, and the latter is 150 seconds on the computer I was testing. We know that StochasticDiffEq.jl has some overhead because of its noise setup for adaptivity, and FWIW we can check for non-adaptive and no events (event handling does need some of this) and then use a simpler noise process. But that's only a 1.5x difference, and only exists when the problem is sufficiently small. This cost is something that, as the cost of `f` and `g` increases, gets eliminated, which has been our main focus. I assume that this difference is not what you're referencing though.

>but in C it would probably be that since the computational time from 1e3 to 1e4 or 1e5 does not grow linearly.

How is that even possible? The number of things to calculate grows linearly. 

Could it be that you're just calculating it differently? Most of our work so far has been focused on fast solving of expensive trajectories, like SPDEs or larger SDEs. In this case, the most cache-optimal thing to do is to split the problem into different tasks and farm them out separately, especially to distribute them. EnsembleThreads and EnsembleDistribute (and EnsembleSplitThreads) are thus embarrassingly-parallel completely independent solves.

However, for this specific case I can guess that you might want to do things differently. Since the full problem is far less than the cache size, it would likely be optimal to stack them as one giant vector and solve it all at once. `EnsembleCPUArray` from [DiffEqGPU.jl](https://github.com/JuliaDiffEq/DiffEqGPU.jl) does precisely this, but mostly to mimic `EnsembleGPUArray` for testing that auto-GPUificaiton approach (and FWIW, automatically building GPU kernels for this problem is may be best. Did you try `EnsembleGPUArray`?)

All of that said, one of the reasons why I did the [ensemble overhaul](http://juliadiffeq.org/2019/07/05/AutomaticSparsity.html) last month was precisely to start tackling this problem. https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/43 explains a bit more. `MultipleTrajectorySDEProblem` is now fully captured in `EnsembleProblem` of `SDEProblem`. So split coupling methods and other methods which improve weak convergence, like 

http://epubs.siam.org/doi/10.1137/15M1040098
https://arxiv.org/abs/1505.00965

should be targeted here. If you'd like to implement methods at that level, you'd just add a dispatch like:

https://github.com/JuliaDiffEq/DiffEqGPU.jl/blob/master/src/DiffEqGPU.jl#L22-L24

>I wanted to ask you if the StochasticDiffEq.jl source code relies in any low level library at all or if it is Julia code written by the JuliaDiffEq team.

All of it is a pure Julia stack written all of the way down. You can follow it all the way through in JuliaDiffEq's repos. I think here it'll mostly be StochasticDiffEq, DiffEqNoiseProcess,and DiffEqBase (which defines the problem types). For more of a description of how it's all setup and why, see:

https://www.sciencedirect.com/science/article/pii/S0965997818310251

So tl;dr:

>let me know if you think we can run fast SDEs simulations using StochasticDiffEq.jl.

Yes, of course! That's what the package is for! But, most of the optimizations have thus far gone into solving more difficult problems like [this Oval2 model](https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/blob/master/src/sde_premade_problems.jl#L152-L298) and discretizations of stochastic partial differential equations. Those have very different performance characteristics because `f` and `g` are expensive enough to cover many details, and so doing more work to decrease the number of `f` and `g` evaluations is the right thing to do. Adaptivity, higher order, etc. are geared towards this, and our benchmarks routinely show massive performance gains by doing so: https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl . And much of this has focused on strong convergence and systems with high stiffness, like biological systems.

However, another thing that shows up, in particular in finance, is small (many time scalar) SDEs with tons of trajectories and only requires weak convergence (mean/variance), and generally no stiffness. In this case, you do need to do some different things, like multi-level Monte Carlo. The ensemble interface was just redone last month so that way these kinds of algorithms could be implemented at the multi-trajectory level, and now we need to go do it. SimpleDiffEq is where some of the tests on these kinds of systems (along with automatic GPU compilation which is a current project) is happening.

And again, if you have any codes for us to benchmark against, it would be great to add it to the common interface. Since the common interface is confederated, you can write your tooling on the interface with your own `DEAlgorithm`, here maybe whatever you currently have wrapped and called from Julia, and then we can use the whole ecosystem of methods to benchmark against it.

**Comment by rvignolo** [comment] 2019-09-14 17:06
Chris,

First of all, thanks for your kind reply, really detailed. However, let's go step by step because I am not that familiar with the DifferentialEquations.jl library. Let's tackle the first problem I encountered. 

> How is that even possible? The number of things to calculate grows linearly.

Okay, that is exactly what I meant, i.e., I would expect to have a linear growth with respect to the number of trajectories. However, when you expect that behavior and it doesn't happen, you probably have a memory leak (in C).
When running `SimpleEM()` algorithm, I encountered the following results issue:
```julia
using SimpleDiffEq
α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
```
I run:
```julia
@time sol = solve(ensembleprob,SimpleEM(),trajectories=npaths,dt=dt)
```
for `1e3, 1e4, 1e5` and `1e6` `npaths`. Results where:
```julia
@time sol = solve(ensembleprob,SimpleEM(),trajectories=1e3,dt=dt)
0.180093 seconds (3.80 M allocations: 70.880 MiB, 7.47% gc time)
EnsembleSolution Solution of length 1000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),trajectories=1e4,dt=dt)
1.631670 seconds (38.01 M allocations: 708.842 MiB, 12.55% gc time)
EnsembleSolution Solution of length 10000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),trajectories=1e5,dt=dt)
15.906248 seconds (380.10 M allocations: 6.922 GiB, 11.27% gc time)
EnsembleSolution Solution of length 100000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),trajectories=1e6,dt=dt)
226.071225 seconds (3.80 G allocations: 69.223 GiB, 31.10% gc time)
EnsembleSolution Solution of length 1000000 with uType:

```
respectively. For all the cases, allocations grow linearly. However, the time grows linearly only for the three first cases, but not for the last one. 

The thing that I don't get is why is this test requieres that amount of allocations. I used to think it was a memory leak, i.e., the algorithm does not free requested memory before allocating new memory or it just ask for a new chunk of memory instead of using a previously allocated one. 

Now, for the other algorithm, `EM()`, I got the following results:
```julia
@time sol = solve(ensembleprob,EM(),trajectories=1e3,dt=dt)
0.247252 seconds (3.89 M allocations: 98.269 MiB, 11.55% gc time)
EnsembleSolution Solution of length 1000 with uType:

@time sol = solve(ensembleprob,EM(),trajectories=1e4,dt=dt)
2.717714 seconds (38.94 M allocations: 982.737 MiB, 29.96% gc time)
EnsembleSolution Solution of length 10000 with uType:

@time sol = solve(ensembleprob,EM(),trajectories=1e5,dt=dt)
 33.881804 seconds (389.40 M allocations: 9.597 GiB, 41.83% gc time)
EnsembleSolution Solution of length 100000 with uType:

```
The last case took a lot of time and return a `Segmentation fault`. Any thoughts? These are my computer's characteristics:

```
Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,1
      Processor Name: Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Hyper-Threading Technology: Enabled
      Memory: 8 GB
```
It should be good enough to run a simple example like this one.

> Could it be that you're just calculating it differently? Most of our work so far has been focused on fast solving of expensive trajectories, like SPDEs or larger SDEs.

Okay, that is perfect. I wanted to test a simple input in order to decide if we can use this library for our project, but our intentions involve running complex trajectories as well as large systems of SDEs.

On the other hand, I will try to understand and implement all your comments in your reply. It will take some time. Thanks for that.

Finally, I wish I could show you some of my `C` implementations for SDE simulations. At the moment, I cannot share them. Just to give you some insight, those routines were added to a [wasora](https://github.com/seamplex/wasora) plugin, a really nice calculation suite that you may or may not find useful sometime ;). 

Thank you for everything, I will be waiting for your reply.

Ramiro.

**Comment by ChrisRackauckas** [comment] 2019-09-14 17:30
>The thing that I don't get is why is this test requires that amount of allocations. I used to think it was a memory leak, i.e., the algorithm does not free requested memory before allocating new memory or it just ask for a new chunk of memory instead of using a previously allocated one.

That doesn't imply a memory leak at all. In fact, Julia has a GC so a pure Julia code should be almost impossible to cause a memory leak (sans a bug in the memory handling of Julia itself). What it's pointing to is that creating a bunch of independent solves, each with their own solution array, is likely a very heavy way to handle this particular problem, and we may accidentally be hitting your RAM limit while multithreading. The GC probably starts to get too involved here. 

>The thing that I don't get is why is this test requires that amount of allocations. I used to think it was a memory leak, i.e., the algorithm does not free requested memory before allocating new memory or it just ask for a new chunk of memory instead of using a previously allocated one.

Likely the workaround for multithreading (with a small type-instability and function-barrier) mentioned below.

>The last case took a lot of time and return a Segmentation fault. In another case, the execution turned off my computer. Any thoughts? 

Possibly a multithreading issue? What version of Julia are you using? Ensembles are using multithreading by default, but it's only experimental until Julia v1.3, so we're kind of the beta testers here. There could be something going on here. We put a let block around the threading loop in

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/ensemble/basic_ensemble_solve.jl#L132-L160

as a workaround for

https://github.com/JuliaLang/julia/issues/15276

but it's not a perfect solution. 

To narrow this down, could you run this without multithreading (`EnsembleSerial`) and `@profile` the result (`Juno.profiler()` or ProfileView.jl to view it). I wonder where it's spending all of its time. You will need to adjust the profiling options or it will certainty segfault on that large of a profile (decrease the sampling frequency). Something is definitely going wrong here, is indicated by the whopping 41% GC time, and I'm not sure what it is.

**Comment by ChrisRackauckas** [comment] 2019-09-14 18:30
You might find this introduction to optimizing Julia helpful here: https://mitmath.github.io/18337/lecture2/optimizing . Essentially what's going on with multithreading is there's a type-instability at the highest level guarded by a function-barrier. That should reduce most of the allocations, but it seems like there's something a little lower as well, which would show up in a flame graph as a tower of inference. Once the allocations go over a certain limit, things will get really bad, since the current GC for the experimental multithreading itself isn't multithreaded (don't know about v1.3-rc1 yet), so that would essentially "stop the world", and my guess is that is what's causing the slowdown.

**Comment by rvignolo** [comment] 2019-09-16 18:48
Chris, 

thanks for your kind replies and sorry for the delay in my response. I've followed your advice and run the following inputs (using `julia version 1.2.0`). First, I will present results for `@time` when using `EnsambleSerial()`:
```julia
using SimpleDiffEq
α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
@time sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=npaths,dt=dt)
```
for `1e3`, `1e4`, `1e5` and `1e6` `npaths`, I got the following results:
```julia
@time sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e3,dt=dt)
  0.151155 seconds (3.80 M allocations: 70.880 MiB, 5.25% gc time)
EnsembleSolution Solution of length 1000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e4,dt=dt)
  1.337427 seconds (38.01 M allocations: 708.842 MiB, 13.63% gc time)
EnsembleSolution Solution of length 10000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e5,dt=dt)
 15.815482 seconds (380.10 M allocations: 6.922 GiB, 18.95% gc time)
EnsembleSolution Solution of length 100000 with uType:

@time sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e6,dt=dt)
191.590133 seconds (3.80 G allocations: 69.223 GiB, 35.12% gc time)
EnsembleSolution Solution of length 1000000 with uType:
```
Then, I profiled the input, but I have not concluded if there is any tower of inference. 
```julia
using SimpleDiffEq, Profile, ProfileView

α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e2,dt=dt)

Profile.init(delay = 1.0)
Profile.clear()
@profile sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e6,dt=dt)

ProfileView.view()
```
Maybe you can check this input in your computer and see if you notice something odd. 

On the other hand, for the `EM()` algorithm, I have tested:
```julia
using DifferentialEquations, Profile, ProfileView

α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
sol = solve(ensembleprob,EM(),EnsembleSerial(),trajectories=1e2,dt=dt)

Profile.init(delay = 0.5)
Profile.clear()
@profile sol = solve(ensembleprob,EM(),EnsembleSerial(),trajectories=3e5,dt=dt)

ProfileView.view()
```
Do you see something strange? 

Lastly, it is not fair to compare something like wasora with something like DifferentialEquations.jl. In wasora, the user writes an input by means of a high-level plain-text input file while in DifferentialEquations.jl the user must write a Julia script. In that sense, the user has to code Julia's functions for `f` and `g`, which are going to be called when computing the `EM()` or `SimpleEM()` steps. In wasora, the user writes a simple input which has to be parsed and translated to C instructions. Being that said, without any kind of parallelization, wasora runs in about 120 sec (for the same kind of SDE with an EM discretization scheme and 1e6 trials).

Thanks and regards,
Ramiro

**Comment by ChrisRackauckas** [comment] 2019-09-16 21:26
>Lastly, it is not fair to compare something like wasora with something like DifferentialEquations.jl. In wasora, the user writes an input by means of a high-level plain-text input file while in DifferentialEquations.jl the user must write a Julia script. In that sense, the user has to code Julia's functions for f and g, which are going to be called when computing the EM() or SimpleEM() steps. In wasora, the user writes a simple input which has to be parsed and translated to C instructions. Being that said, without any kind of parallelization, wasora runs in about 120 sec (for the same kind of SDE with an EM discretization scheme and 1e6 trials).

It should be comparable. Julia compiles down to LLVM the same way that Clang does, so if everything goes correctly then the two should be the same. Being off by ~2x means that the array formulation in wasora is probably allowing SIMD to occur, while SIMD won't occur in this form of ensembling. That would account for the difference.

**Comment by rvignolo** [comment] 2019-09-16 22:39
Hi Chris,

Just to be clear, at the moment, I don't want or need to compare the computational time between C and Julia implementations of SDE simulations. Being that said, I will make the last comment about this but then let's move forward and try to find out why my computer runs out of memory and shuts down when I try to run a simple SDE simulation using DifferentialEquations.jl.

## Last comment:
I have implemented several discretization schemes in C and embedded them into the wasora-suite framework. These schemes include the following cases:
```C
enum {
    EulerMaruyama,               // Explicit Order 0.5 Strong or 1.0 Weak Scheme
    LogEulerMaruyama,            // Explicit Order 0.5 Strong or 1.0 Weak Scheme
    PredictorCorrector,          // Explicit Order 1.0 Weak Scheme
    ExplicitMilsteinPlaten,      // Explicit Order 1.0 Strong Scheme
    ExplicitMilsteinAndersen,    // Explicit Order 2.0 Weak Scheme
    ExplicitPlatenWagner,        // Explicit Order 1.5 Strong Scheme
  } scheme;
```
For those schemes, you have to provide functions `f` and `g` (i.e. the drift vector and diffusion matrix).  In DifferentialEquations.jl, those functions are provided as Julia routines, while in the wasora framework, they are provided in an input file that has to be parsed and interpreted. Then, in wasora source code, when you want to evaluate those functions, you have to call to [this](https://github.com/seamplex/wasora/blob/f1b82434e4543fd6cfafced92afdeab9da418e19/src/algebra.c#L31) function, which should be much more expensive than Julia `f` and `g` functions. This is the main reason why I would expect DifferentialEquations.jl to be **much** faster than my C implementation (which does not include any SIMD programming).

Once I figure out if we can use DifferentialEquations.jl for our project, I will benchmark your SDE schemes with our implementations and compare the computational times, etc. Also, we can add new discretizations as well as implement financial models. 

## Main issue
So,  going back to the main issue, do you have any ideas how can we fix the problem with this simple input and the shutdown of a computer? Have you seen anything strange in the `@profile`s described above?

**Comment by ChrisRackauckas** [comment] 2019-09-16 23:22
Or are you saying that wasora isn't parsing it to compile a C function?

**Comment by rvignolo** [comment] 2019-09-16 23:45
to simulate an autonomous SDE given by:
```
dX(t) = f(X) dt + g(X) dW(t)
```
with `f(X) = 0.4 * X` and `g(X) = 0.03 * X` you have to write an input file by means of a high-level plain-text file (**which is not in C!!**), like the following:
```
# define drift function
f(x) := 0.4 * x

# define diffusion function
g(X) := 0.03 * x

PROCESS {
  NAME X
  DRIFT     f(X_t)   # X_t is a variable that takes de value of X(t) at the corresponding time
  DIFFUSION g(X_t)
  SCHEME EulerMaruyama
}
```
Then, when you simulate the SDE, you have to evaluate both drift and diffusion expressions. So, since they have been provided in wasora's input syntax, they have to be translated to C code by means of a parser that builds expressions in the form of trees. Then, when you evaluate one of those expressions, you move over a tree of instructions and compute the result, which is much more expensive than if the user provides a dynamically-loaded routine (DLL) for `f` and `g` such as:
```C
double f(double x) {
  return 0.4 * x;
}

double g(double x) {
  return 0.03 * x;
}
```
On the other hand, in DifferentialEquations.jl, the user provides `f` and `g` directly in Julia, so it should be faster.

Any ideas regarding the main issue?

**Comment by ChrisRackauckas** [comment] 2019-09-16 23:45
Ohhhhh... I found out what it is... I don't know how I missed it 😄 

```julia
using SimpleDiffEq, Profile, ProfileView

α=1
β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
using BenchmarkTools
@btime sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e3,dt=dt)
```

gives

``julia
30.546 ms (2292532 allocations: 40.24 MiB)
```

while 

```julia
using SimpleDiffEq, Profile, ProfileView

const α=1
const β=1
u₀=1/2
f(u,p,t) = α*u
g(u,p,t) = β*u
dt = 1/252
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,tspan)
ensembleprob = EnsembleProblem(prob)
using BenchmarkTools
@btime sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e3,dt=dt)
```

gives

```julia
4.159 ms (24532 allocations: 5.63 MiB)
```

This is because using a non-constant global inside of a function is a performance killer, and it's the number 1 performance nono.

https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Avoid-global-variables-1

I explain in depth what happens in this article:

http://ucidatascienceinitiative.github.io/IntroToJulia/Html/WhyJulia

To make sure it's not just Julia specializing on the constants, you can run it in a way that localizes the parameters:

```julia
using SimpleDiffEq, Profile, ProfileView

u₀=1/2
f(u,p,t) = p[1]*u
g(u,p,t) = p[2]*u
dt = 1/252
tspan = (0.0,1.0)
p = (1,1)
prob = SDEProblem(f,g,u₀,tspan,p)
ensembleprob = EnsembleProblem(prob)
using BenchmarkTools
@btime sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e3,dt=dt)
```

which gives me 

```julia
3.797 ms (24532 allocations: 5.68 MiB)
```

So then

```julia
using SimpleDiffEq
u₀=1/2
f(u,p,t) = p[1]*u
g(u,p,t) = p[2]*u
dt = 1/252
tspan = (0.0,1.0)
p = (1,1)
prob = SDEProblem(f,g,u₀,tspan,p)
ensembleprob = EnsembleProblem(prob)
using BenchmarkTools
@btime sol = solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e6,dt=dt)
```

takes `8.781 s (24999534 allocations: 5.55 GiB)` on my laptop.

**Comment by rvignolo** [comment] 2019-09-16 23:47
this looks promising! Thank you very much, let me check it! I just commented on top of your comment 1 sec before you haha

**Comment by rvignolo** [comment] 2019-09-16 23:51
Oh, that is correct, I get it! Thank you very much! Will test it ASAP.

**Comment by ChrisRackauckas** [comment] 2019-09-18 15:58
It looks like this is solved so I'm closing it. But let's keep discussing if you're interested in doing development, either on model libraries or the solver methods. There's a ton to do in this area, and this thread mentions a billion things we could improve.

**Closed by ChrisRackauckas** 2019-09-18 15:58 UTC

**Comment by rvignolo** [comment] 2019-09-19 00:26
Hi Chris, 

I would like to thank you again for your kind help. For the moment, I will be building a lot of infrastructure on top of DifferentialEquations.jl but once I get that done I will be able to perform many tests. 

Probably I will get really involved with this library and, in that case, I will contribute accordingly. 

Thanks!

**Comment by MFairley** [comment] 2020-04-30 04:20
@ChrisRackauckas I noticed a red type instability warning with @code_warntype on my own EnsembleProblems and also the corrected example in this issue 

```
@code_warntype solve(ensembleprob,SimpleEM(),EnsembleSerial(),trajectories=1e3,dt=dt)
Variables
  #unused#::Core.Compiler.Const(DiffEqBase.var"#solve##kw"(), false)
  @_2::NamedTuple{(:trajectories, :dt),Tuple{Float64,Float64}}
  @_3::Core.Compiler.Const(DiffEqBase.solve, false)
  prob::EnsembleProblem{SDEProblem{Float64,Tuple{Float64,Float64},false,DiffEqBase.NullParameters,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Nothing},DiffEqBase.var"#340#346",DiffEqBase.var"#339#345",DiffEqBase.var"#341#347",Array{Any,1}}
  args::Core.Compiler.Const((SimpleEM(), EnsembleSerial()), false)
  kwargs...::Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol,Symbol},NamedTuple{(:trajectories, :dt),Tuple{Float64,Float64}}}

Body::EnsembleSolution{_A,_B,_C} where _C where _B where _A
1 ─      (kwargs... = Base.pairs(@_2))
│   %2 = Core.tuple(kwargs..., @_3, prob)::Core.Compiler.PartialStruct(Tuple{Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol,Symbol},NamedTuple{(:trajectories, :dt),Tuple{Float64,Float64}}},typeof(solve),EnsembleProblem{SDEProblem{Float64,Tuple{Float64,Float64},false,DiffEqBase.NullParameters,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Nothing},DiffEqBase.var"#340#346",DiffEqBase.var"#339#345",DiffEqBase.var"#341#347",Array{Any,1}}}, Any[Base.Iterators.Pairs{Symbol,Float64,Tuple{Symbol,Symbol},NamedTuple{(:trajectories, :dt),Tuple{Float64,Float64}}}, Core.Compiler.Const(DiffEqBase.solve, false), EnsembleProblem{SDEProblem{Float64,Tuple{Float64,Float64},false,DiffEqBase.NullParameters,Nothing,SDEFunction{false,typeof(f),typeof(g),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(g),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Nothing},DiffEqBase.var"#340#346",DiffEqBase.var"#339#345",DiffEqBase.var"#341#347",Array{Any,1}}])
│   %3 = Core._apply_iterate(Base.iterate, DiffEqBase.:(var"#solve#469"), %2, args)::EnsembleSolution{_A,_B,_C} where _C where _B where _A
└──      return %3
```

The red part is `::EnsembleSolution{_A,_B,_C} where _C where _B where _A` Is this expected and is there any performance hit from this?

**Comment by ChrisRackauckas** [comment] 2020-04-30 10:02
Julia is unable to infer the result of the pmap, so it returns a `Vector{Any}` which we then wrap back into a concrete typed array:

https://github.com/SciML/DiffEqBase.jl/blob/master/src/ensemble/basic_ensemble_solve.jl#L137

We can probably dig into there with `Base.return_type` and directly infer the result for Base, but it's almost always not a major computational time issue since the DE solver are usually an order of magnitude if not more than the "shuttling around" cost. That said, it's never bad to make it better.
