### ISSUE TITLE
SDEProblem(..., noise=NoiseWrapper(OrnsteinUhlenbeckProcess!(...))) does not work with adaptive method

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/StochasticDiffEq.jl#37] opened 2017-08-27 04:45 UTC
I thought I'd use `NoiseWrapper(OrnsteinUhlenbeckProcess!(...))` until the bridge distribution is implemented for Ornstein-Uhlenbeck Process to use adaptive method.  But it didn't work:

```julia
oup = OrnsteinUhlenbeckProcess!(1.0, 0.0, 1.0, 0.0, [0.0], [0.0])
noise = NoiseWrapper(oup)
prob = SDEProblem((t, u) -> -u, (t, u) -> 1.0, [0.0], (0.0, 1.0), noise=noise)
sol = solve(prob)
```

Note that `solve(prob, dt=1e-3, adaptive=false)` works.  Above code failed with `DimensionMismatch` error:

<details>

```
ERROR: DimensionMismatch("Cannot left-divide transposed vector by matrix")
Stacktrace:
 [1] perform_step! at ~/.julia/v0.6/StochasticDiffEq/src/integrators/sri.jl:293 [inlined]
 [2] perform_step! at ~/.julia/v0.6/StochasticDiffEq/src/integrators/sri.jl:262 [inlined]
 [3] solve!(::StochasticDiffEq.SDEIntegrator{StochasticDiffEq.SRIW1,Array{Float64,1},Float64,Float64,Float64,Float64,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},Array{Float64,1},DiffEqBase.RODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void},StochasticDiffEq.SRIW1,StochasticDiffEq.LinearInterpolationData{Array{Array{Float64,1},1},Array{Float64,1}}},StochasticDiffEq.SRIW1ConstantCache,Void,##109#111,##110#112,StochasticDiffEq.SDEOptions{Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Void,Void,Float64,Float64,Float64,Float64},DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true}}) at ~/.julia/v0.6/StochasticDiffEq/src/solve.jl:391
 [4] #solve#58(::Array{Any,1}, ::Function, ::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}, ::StochasticDiffEq.SRIW1, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at ~/.julia/v0.6/StochasticDiffEq/src/solve.jl:7
 [5] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}, ::StochasticDiffEq.SRIW1, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at ./<missing>:0 (repeats 2 times)
 [6] #solve#2(::Bool, ::Array{Any,1}, ::Function, ::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}, ::Void) at ~/.julia/v0.6/DifferentialEquations/src/default_solve.jl:14
 [7] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}, ::Void) at ./<missing>:0
 [8] #solve#1(::Bool, ::Array{Any,1}, ::Function, ::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}) at ~/.julia/v0.6/DifferentialEquations/src/default_solve.jl:5
 [9] solve(::DiffEqBase.SDEProblem{Array{Float64,1},Float64,false,DiffEqNoiseProcess.NoiseWrapper{Float64,2,Float64,Array{Float64,1},Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.OrnsteinUhlenbeck!{Float64,Float64,Float64},Void,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Array{Float64,1},1},true},##109#111,##110#112,Void,UniformScaling{Int64},Void}) at ~/.julia/v0.6/DifferentialEquations/src/default_solve.jl:2
 [10] macro expansion at ./REPL.jl:97 [inlined]
 [11] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

</details>

**Comment by ChrisRackauckas** [comment] 2017-08-27 04:49
Try it with an inplace problem. The out-of-place version is likely missing a `.`.

**Comment by tkf** [comment] 2017-08-27 04:51
Got the same `ERROR: DimensionMismatch("Cannot left-divide transposed vector by matrix")` with `oup = OrnsteinUhlenbeckProcess(1.0, 0.0, 1.0, 0.0, [0.0], [0.0])`.

**Comment by ChrisRackauckas** [comment] 2017-08-27 04:53
Nono, not out-of-place noise. An inplace problem.

```julia
oup = OrnsteinUhlenbeckProcess!(1.0, 0.0, 1.0, 0.0, [0.0], [0.0])
noise = NoiseWrapper(oup)
prob = SDEProblem((t, u,du) -> du.=-u, (t, u,du) -> du.=1.0, [0.0], (0.0, 1.0), noise=noise)
sol = solve(prob)
```

out-of-place with vectors mostly works, but in general you should always use an inplace function with vectors anyways to stop heap allocations so vectors+out-of-place isn't well tested.

**Comment by tkf** [comment] 2017-08-27 05:04
Oops.  Sorry, I totally miss-read your sentence.  Since I usually use in-place problem, the current implementation is fine for me then.  Please close the issue if you want to open issues minimal.

BTW, the error is happening at 

```julia
integrator.EEst = integrator.opts.internalnorm(@muladd(integrator.opts.delta*E₁+E₂)/(@muladd(integrator.opts.abstol + max.(abs.(uprev),abs.(u))*integrator.opts.reltol)))
```

in sri.jl.  When I `@show` the two `@muladd(...)` terms (numerator and denominator), both of them were vectors.  This is just my random guess, but maybe you wanted to wrap both with `internalnorm`, like this?:

```julia
integrator.EEst = integrator.opts.internalnorm(@muladd(integrator.opts.delta*E₁+E₂))/integrator.opts.internalnorm(@muladd(integrator.opts.abstol + max.(abs.(uprev),abs.(u))*integrator.opts.reltol))
```

**Comment by ChrisRackauckas** [comment] 2017-08-27 05:07
No, it should be the norm of the normalized error. The issue is that it should be `./` instead of `/`.

**Comment by tkf** [comment] 2017-08-27 05:17
I see.

**Comment by ChrisRackauckas** [comment] 2017-10-02 02:26
Labelling for Hacktoberfest. Should be as simple as making `internalnorm` calls use `./` instead of `/`, and adding tests.

**Comment by ChrisRackauckas** [comment] 2017-11-03 15:52
Fixed by https://github.com/JuliaDiffEq/StochasticDiffEq.jl/commit/cfe7d0ebdb768197b8a51dbe09724303339aeef0

**Closed by ChrisRackauckas** 2017-11-03 15:52 UTC
Labels: Hacktoberfest
